build:
    docker image build -t celeb-matcher/backend .

# Run this to recompile requirements.txt when requirements.ini changes.
update-deps:
    pip-compile --strip-extras requirements.ini
    pip install -r requirements.txt