build:
    docker image build -t celeb-matcher/backend .

# Run this to recompile requirements.txt when requirements.ini changes.
update-deps:
    pip-compile --strip-extras requirements.ini
    PIP_REQUIRE_VIRTUALENV=1 pip install -r requirements.txt